name: Detener EC2 y RDS

on:
  schedule:
    # 12:00 VET Lunes-Sábado = 16:00 UTC (apagado del mediodía)
    - cron:  '0 16 * * 1-6'
  workflow_dispatch: {}

jobs:
  stop:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      EC2_ID: i-01b29862c501519bd
      RDS_ID: arow-db

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:            ${{ env.AWS_REGION }}

    - name: Detener instancia EC2
      run: |
        set -euo pipefail
        aws ec2 stop-instances --instance-ids $EC2_ID
        aws ec2 wait instance-stopped --instance-ids $EC2_ID

    - name: Verificar estado EC2
      run: |
        set -euo pipefail
        aws ec2 describe-instances --instance-ids "$EC2_ID" --query 'Reservations[0].Instances[0].State.Name' --output text

    - name: Detener instancia RDS
      run: |
        set -euo pipefail
        aws rds stop-db-instance --db-instance-identifier $RDS_ID
        aws rds wait db-instance-stopped --db-instance-identifier $RDS_ID

    - name: Verificar estado RDS
      run: |
        set -euo pipefail
        aws rds describe-db-instances --db-instance-identifier "$RDS_ID" --query 'DBInstances[0].DBInstanceStatus' --output text
